package javaee.jdbc.source.pooled;

import javax.sql.ConnectionEvent;

/**
 * An object that registers to be notified of events generated by a
 * <code>PooledConnection</code> object.
 *
 * @see java.util.EventListener
 * @see javax.sql.ConnectionEvent
 * @see javax.sql.PooledConnection
 * @see javax.sql.ConnectionEventListener
 */
public interface ConnectionEventListener extends javax.sql.ConnectionEventListener {

    void connectionClosed(ConnectionEvent event);
    void connectionErrorOccurred(ConnectionEvent event);

}
